### ISSUE TITLE
Front Matter causes error with sass-embedded

### ISSUE THREAD

**Issue by qiz-li** [jekyll/jekyll-sass-converter#135] opened 2022-03-25 03:21 UTC
Hi. I am trying to move to `sass-embedded` to use `@use`. In my Gemfile, I have

```ruby
gem 'sass-embedded', '~> 1.0'
```

and I also changed the implementation in `_config.yml`

```yaml
sass:
  implementation: sass-embedded
```

However when I try to serve the Jekyll site, it causes this error:

```
Configuration file: /Users/qiz-li/my_jekyll/_config.yml
            Source: /Users/qiz-li/my_jekyll
       Destination: /Users/qiz-li/my_jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Error: expected "{".
  ╷
4 │ @import "main";
  │               ^
  ╵
  assets/css/main.scss 4:15  @import
  assets/css/main.scss 1:9   root stylesheet
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    expected "{".
/Users/qiz-li/.gem/ruby/3.1.0/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:223:in `rescue in sass_embedded_convert': expected "{". (Jekyll::Converters::Scss::SyntaxError)
        from /Users/qiz-li/.gem/ruby/3.1.0/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:214:in `sass_embedded_convert'
```

When I change the implementation back to `implementation: sassc` the error disappears, and Jekyll serves fine.
I have not changed the contents of the Sass files.

**`assets/css/main.scss:`**

```scss
---
---

@import "main";
```

**`_sass/main.scss:`**

```scss
$backgroundColor: #ffffff;
$bodyColor: #000000;
$bodyFont: -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";

body {
  background: $backgroundColor;
  color: $bodyColor;
  font-family: $bodyFont;
}
```

I am on:

- Ruby: `ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-darwin21]`
- OS: `macOS Monterey Version 12.2.1`

Thanks for any help.

**Comment by ashmaroli** [comment] 2022-03-25 09:20
/cc @ntkme Will you be able to diagnose the cause here?
Thanks either ways.

**Comment by ntkme** [comment] 2022-03-25 09:29
The issue is not really due to front matter. It is due to both of your files have the same name `main.scss`, that sass-embedded will try to resolve the file relative to the input path, which means the file itself with the front matter is imported by itself.

**Comment by ashmaroli** [comment] 2022-03-25 09:49
> It is due to both of your files have the same name `main.scss`,

@ntkme That's strange. Since `assets/css/main.scss` wouldn't (shouldn't) be in the `sass_load_paths`, how is the file trying to import itself?

**Comment by ntkme** [comment] 2022-03-25 10:00
This is where importer behave has change for dart-sass. In dart-sass load path is searched only if relative path is not found. When using `compile_string`, the location of input file is set by the `url` argument:

https://github.com/jekyll/jekyll-sass-converter/blob/41740374682ea691207c267cfbcca7ea30438b91/lib/jekyll/converters/scss.rb#L210

Reference:

https://sass-lang.com/documentation/js-api/interfaces/StringOptionsWithImporter#importer

> A relative load's URL is first resolved relative to [url](https://sass-lang.com/documentation/js-api/interfaces/StringOptionsWithImporter#url), then passed to [importer](https://sass-lang.com/documentation/js-api/interfaces/StringOptionsWithImporter#importer). If the importer doesn't recognize it, it's then passed to [importers](https://sass-lang.com/documentation/js-api/interfaces/StringOptionsWithImporter#importers) and [loadPaths](https://sass-lang.com/documentation/js-api/interfaces/StringOptionsWithImporter#loadPaths).

**Comment by ashmaroli** [comment] 2022-03-25 10:04
Ah! I see.
@ntkme If possible, could you add a section to our README noting down the apparent differences between dart-sass and older impls?
Thanks in advance.

**Comment by ntkme** [comment] 2022-03-25 10:11
Actually I just found another documentation that conflicts with what we see: https://sass-lang.com/documentation/js-api/interfaces/StringOptionsWithoutImporter#url

> If `url` isn't passed along with `StringOptionsWithoutImporter.importer`, it's optional and **only used for error reporting**.

Ruby sass-embedded host is just passing those arguments as is to dart-sass-embedded, so that there might be some issue in upstream. I will do some tests on this and maybe ask upstream dart-sass project when I get a chance.

**Comment by ntkme** [comment] 2022-03-25 17:09
I confirmed the official node sass-embedded host have the exactly same behavior as ruby sass-embedded host.

**Comment by ashmaroli** [comment] 2022-03-25 17:37
So, is this an upstream bug or a new quirk?

**Comment by ntkme** [comment] 2022-03-25 17:37
https://github.com/sass/dart-sass/issues/1657

**Comment by ntkme** [comment] 2022-03-25 18:02
@ashmaroli Another question would be whether this behavior is desirable or not. If it is not desirable, we can probably add a prefix to url to make it not resolvable by sass, thus force the lookup to be in load_paths, for which the url option can still be kept for error reporting:

``` diff
diff --git a/lib/jekyll/converters/scss.rb b/lib/jekyll/converters/scss.rb
index 5dbd6b9..481a2f5 100644
--- a/lib/jekyll/converters/scss.rb
+++ b/lib/jekyll/converters/scss.rb
@@ -244,7 +244,7 @@ module Jekyll
       def sass_file_url
         return if associate_page_failed?
 
-        file_url_from_path(File.join(site_source, sass_page.relative_path))
+        "jekyll-sass-converter:" + file_url_from_path(File.join(site_source, sass_page.relative_path))
       end
 
       # The value of the `line_comments` option.
```

**Comment by ashmaroli** [comment] 2022-03-25 18:13
Bit of stalemate here.
Ideally, having as much parity between `sassc` and `dart-sass` would be the goto option. But having disparity between `node-sass` and our implementation is going to create confusion.

Lets wait this one out..

**Comment by ntkme** [comment] 2022-05-20 15:59
Upstream has decided to keep the current behavior (relative resolve works against entrypoint if `url` parameter is a `file://` URL).

@ashmaroli Do you want to add a note to README? Also maybe we should call out that GitHub pages uses an old version of this project so that what the README won't work when directly build with GHP and people need to run custom action if they prefer to use new features.

**Comment by ashmaroli** [comment] 2022-05-20 16:52
Thank you for getting back on this @ntkme.
Since upstream has decided to keep current behavior, let us go ahead with your previous suggestion:
> we can probably add a prefix to url to make it not resolvable by sass, thus force the import lookup to be in load_paths,

But let it be *togglable* such that users wishing to have parity with node-sass may do so with an entry in their config file.

**Comment by ntkme** [comment] 2022-11-06 04:30
@ashmaroli I think we can close this as "won't fix". `sass-embedded` implementation has different behavior and the difference is now documented.

**Closed** 2022-11-06 05:54 UTC
Labels: has-pull-request
